<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260226150115 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE "availability" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date DATE NOT NULL, available BOOLEAN NOT NULL, locked BOOLEAN NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_3FB7A2BFA76ED395 ON "availability" (user_id)');
        $this->addSql('CREATE UNIQUE INDEX USER_UNIQUE_DAY ON "availability" (user_id, date)');
        $this->addSql('CREATE TABLE "game" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, active BOOLEAN NOT NULL, owner_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_232B318C7E3C61F9 ON "game" (owner_id)');
        $this->addSql('CREATE TABLE game_players (game_id INT NOT NULL, user_id INT NOT NULL, PRIMARY KEY (game_id, user_id))');
        $this->addSql('CREATE INDEX IDX_B38C3C89E48FD905 ON game_players (game_id)');
        $this->addSql('CREATE INDEX IDX_B38C3C89A76ED395 ON game_players (user_id)');
        $this->addSql('CREATE TABLE game_session (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date DATE NOT NULL, game_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_4586AAFBE48FD905 ON game_session (game_id)');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, name VARCHAR(255) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) DEFAULT NULL, google_id VARCHAR(255) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D93D64976F5C865 ON "user" (google_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON "user" (email)');
        $this->addSql('ALTER TABLE "availability" ADD CONSTRAINT FK_3FB7A2BFA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE "game" ADD CONSTRAINT FK_232B318C7E3C61F9 FOREIGN KEY (owner_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE game_players ADD CONSTRAINT FK_B38C3C89E48FD905 FOREIGN KEY (game_id) REFERENCES "game" (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE game_players ADD CONSTRAINT FK_B38C3C89A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE game_session ADD CONSTRAINT FK_4586AAFBE48FD905 FOREIGN KEY (game_id) REFERENCES "game" (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE "availability" DROP CONSTRAINT FK_3FB7A2BFA76ED395');
        $this->addSql('ALTER TABLE "game" DROP CONSTRAINT FK_232B318C7E3C61F9');
        $this->addSql('ALTER TABLE game_players DROP CONSTRAINT FK_B38C3C89E48FD905');
        $this->addSql('ALTER TABLE game_players DROP CONSTRAINT FK_B38C3C89A76ED395');
        $this->addSql('ALTER TABLE game_session DROP CONSTRAINT FK_4586AAFBE48FD905');
        $this->addSql('DROP TABLE "availability"');
        $this->addSql('DROP TABLE "game"');
        $this->addSql('DROP TABLE game_players');
        $this->addSql('DROP TABLE game_session');
        $this->addSql('DROP TABLE "user"');
    }
}
